name: aquavision_mobile
description: AquaVision Flutter mobile app
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter: { sdk: flutter }
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  dio: ^5.5.0+1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  image: ^4.2.0
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.1
  shared_preferences: ^2.2.3
  # Additional packages for enhanced UI and functionality
  animate_do: ^3.3.4
  lottie: ^3.1.2
  shimmer: ^3.0.0
  fluttertoast: ^8.2.6
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/header_bg.jpg
    - assets/fish_sample.jpeg
    - assets/fish1.jpeg
    - assets/fish2.jpeg
    - assets/fish3.jpg
    - assets/data/fish_species.json


